/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#3c0800',
        'on-secondary-fixed': '#131d20',
        'secondary-fixed': '#dae4e8',
        'on-tertiary-fixed-variant': '#7c2e19',
        surface: '#121414',
        'tertiary-fixed': '#ffdbd2',
        'on-primary-container': '#1b3b35',
        'on-primary-fixed': '#00201b',
        tertiary: '#ffb4a1',
        'surface-dim': '#121414',
        'on-surface': '#e2e2e2',
        secondary: '#bec8cc',
        'on-primary-fixed-variant': '#2d4c46',
        'error-container': '#93000a',
        'tertiary-container': '#ea8266',
        'surface-bright': '#383939',
        'primary-container': '#84a59d',
        'surface-container-lowest': '#0d0f0f',
        'surface-container-high': '#282a2a',
        error: '#ffb4ab',
        'surface-container': '#1e2020',
        primary: '#accec5',
        'on-tertiary': '#5d1805',
        'primary-fixed-dim': '#accec5',
        'secondary-fixed-dim': '#bec8cc',
        'tertiary-fixed-dim': '#ffb4a1',
        'on-secondary-fixed-variant': '#3e484c',
        'secondary-container': '#3e484c',
        'on-surface-variant': '#c1c8c5',
        'surface-tint': '#accec5',
        'surface-variant': '#333535',
        'on-error': '#690005',
        'on-primary': '#163630',
        'on-tertiary-container': '#651d09',
        'inverse-primary': '#45645e',
        'inverse-on-surface': '#2f3131',
        'outline-variant': '#414846',
        outline: '#8b9290',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#acb7ba',
        background: '#121414',
        'surface-container-low': '#1a1c1c',
        'on-secondary': '#283235',
        'inverse-surface': '#e2e2e2',
        'primary-fixed': '#c7eae1',
        'on-background': '#e2e2e2',
        'surface-container-highest': '#333535',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      transitionDuration: {
        DEFAULT: '300ms',
      },
      boxShadow: {
        'recorder-glow': '0 0 50px rgba(172, 206, 197, 0.3)',
        'fab-ambient': '0 0 32px rgba(226, 226, 226, 0.06)',
      },
    },
  },
  plugins: [],
};
